<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="7">
            <File firstVisibleLine="0" xOffset="0" scrollWidth="624" startPos="0" endPos="0" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Downloads\perpustakaan_saskia.sql" backupFilePath="" originalFileLastModifTimestamp="1754525782" originalFileLastModifTimestampHigh="31130251" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="560" startPos="2891" endPos="2891" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Downloads\Perpustakaan_Saskia 2.sql" backupFilePath="" originalFileLastModifTimestamp="-327682281" originalFileLastModifTimestampHigh="31130251" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="560" startPos="2891" endPos="2891" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Downloads\Saskia Dahayu C\perpustakaan_saski3.sql" backupFilePath="" originalFileLastModifTimestamp="1993571125" originalFileLastModifTimestampHigh="31130252" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="197" xOffset="0" scrollWidth="520" startPos="6347" endPos="6347" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Downloads\Saskia Dahayu C\perpustakaan_saskia4.sql" backupFilePath="" originalFileLastModifTimestamp="1378528232" originalFileLastModifTimestampHigh="31130253" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="197" xOffset="0" scrollWidth="520" startPos="6763" endPos="6763" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Documents\perpustakaan_2.sql" backupFilePath="" originalFileLastModifTimestamp="-1139519130" originalFileLastModifTimestampHigh="31130253" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="81" xOffset="0" scrollWidth="536" startPos="2169" endPos="2169" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Documents\ANDES Fildzah\perpustakaan-sederhana-fildzah.sql" backupFilePath="" originalFileLastModifTimestamp="-1909486174" originalFileLastModifTimestampHigh="31130446" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="624" startPos="327" endPos="327" selMode="0" offset="0" wrapCount="1" lang="SQL" encoding="-1" userReadOnly="no" filename="D:\Documents\ANDES Fildzah\perpustakaan-sederhana-fildzah2.sql" backupFilePath="C:\Users\HP\AppData\Roaming\Notepad++\backup\perpustakaan-sederhana-fildzah2.sql@2024-09-10_140847" originalFileLastModifTimestamp="-1357482389" originalFileLastModifTimestampHigh="31130447" tabColourId="-1" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="512" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
